### Get all movies (JSON format)
GET http://localhost:3000/movies/json
### Get movies (HTML list format)
GET http://localhost:3000/movies
### Get a specific movie by ID 
GET http://localhost:3000/movies/6748ec91ad7268f261cc9e8a
### Create a new movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Shrek Forever After",
  "director": "Mike Mitchell",
  "year": 2010
}
### Update an existing movie 
PUT http://localhost:3000/movies/673e12ed1eac26a4aedff262
Content-Type: application/json

{
  "title": "Inception Updated",
  "director": "Christopher Nolan Updated",
  "year": 2011
}

### Delete a movie
DELETE http://localhost:3000/movies/6748ed4d4f0b9587d57d3de9
### Try to get a non-existent movie (should return 404)
GET http://localhost:3000/999
### Test the catch-all route (should return 404)
GET http://localhost:3000/route-that-doesnt-exist
### get movies with 2010 year
GET http://localhost:3000/movies?year=2010
### get moives with Noland && year == 2010
GET http://localhost:3000/movies?year=2010&director=Mike Mitchell

### Login Test - Valid Credentials
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

### Create a new movie
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGExMDJlM2IyZTQyYTVmZWY1NDAyZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMjkwNzA2OCwiZXhwIjoxNzMyOTEwNjY4fQ.yi0DMYhhB0VpqrL611zYj7iIXv32UqiH1elyWB1n8Gk

{
  "title": "Shrek",
  "director": "Andrew Adamson, Vicky Jenson",
  "year": 2001
}
